WebApplication1/Controllers/FansController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebApplication1.Models;

namespace WebApplication1.Controllers
{
    [Authorize]
    public class FansController : Controller
    {
        private BlogContext db = new BlogContext();

        // GET: Fans
        [AllowAnonymous]
        public ActionResult Index(string firstName, string country, string gender)
        {
            /* Create gender list from the genders in th db */
            var GenderList = new List<string>();

            var GenderQry = from d in db.Fans
                           orderby d.Gender
                           select d.Gender;

            GenderList.AddRange(GenderQry.Distinct());
            // Put in viewbag in order to use as a dropdownn list in the view (razor)
            ViewBag.gender = new SelectList(GenderList);

            // Get all fans
            var fans = from f in db.Fans
                         select f;

            // Filter fans
            if (!String.IsNullOrEmpty(firstName))
            {
                fans = fans.Where(f => f.FirstName.Contains(firstName));
            }

            if (!String.IsNullOrEmpty(country))
            {
                fans = fans.Where(f => f.Country.Contains(country));
            }

            if (!String.IsNullOrEmpty(gender))
            {
                fans = fans.Where(x => x.Gender == gender);
            }

            return View(fans.ToList());
        }

        // GET: Fans/Details/5
        [AllowAnonymous]

        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fan fan = db.Fans.Find(id);
            if (fan == null)
            {
                return HttpNotFound();
            }
            return View(fan);
        }

        // GET: Fans/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Fans/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,FirstName,LastName,Gender,BirthDay,Country")] Fan fan)
        {
            if (ModelState.IsValid)
            {
                db.Fans.Add(fan);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(fan);
        }

        // GET: Fans/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fan fan = db.Fans.Find(id);
            if (fan == null)
            {
                return HttpNotFound();
            }
            return View(fan);
        }

        // POST: Fans/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,FirstName,LastName,Gender,BirthDay,Country")] Fan fan)
        {
            if (ModelState.IsValid)
            {
                db.Entry(fan).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(fan);
        }

        // GET: Fans/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Fan fan = db.Fans.Find(id);
            if (fan == null)
            {
                return HttpNotFound();
            }
            return View(fan);
        }

        // POST: Fans/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Fan fan = db.Fans.Find(id);
            db.Fans.Remove(fan);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebApplication1/Views/Shared/_Layout.cshtml
<!-- Or Gabay 307858712 Eilon Lotem 305236770 -->
<!doctype html>
<html>
<head>
    <title>Shauli</title>
    @*<audio autoplay loop>
        <source src="/Content/Minions Banana.mp3" type="audio/mpeg">
        Your browser does not support the audio element.
    </audio>*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <header>
        <h1 id="maintitle">Ha-Blog Shel Shauli</h1>
    </header>
    <nav>
        <!-- Navigation -->
        <ul id="navbar">
            <li id="navblog">@Html.ActionLink("Blog", "Index", "Blog")</li>
            <li id="navabout">@Html.ActionLink("About", "About", "Blog")</li>
            <li id="navfans">@Html.ActionLink("Fan Club","Index", "Fans")</li>
            <li id="navstats">@Html.ActionLink("Statistics", "Statistics", "Blog")</li>
            <li class="subscribe">
                <div id="transDemo2">
                    <img src="/Content/images/facebook.png" width="25" height="25">
                </div>
                <a id="shareBtn" href="#">Share on Facebook</a>
            </li>
        </ul>
    </nav>
    <section id="intro">
        <!-- Introduction -->

        <header>
            <h2>Do you have questions for me?</h2>
        </header>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut.</p>
        <img src="/Content/images/intro_shauli.png" alt="Shauli" />
    </section>
    <div id="content">
        <div id="mainContent">
            @RenderBody()
        </div>
        <aside>
            <section id="weatherWrap">
                <header>
                    <h3>Our Centers Weather</h3>
                </header>
                <select id="cities" class="form-control">
                    <option value="Tel Aviv">Tel Aviv</option>
                    <option value="Roma">Roma</option>
                    <option value="Madrid">Madrid</option>
                    <option value="Berlin">Berlin</option>
                </select>
                <div id="weatherRes">
                </div>
                <button type="button" class="btn btn-default">Get Weather</button>
            </section>
            <span>
                @Html.Partial("_LoginPartial")
            </span>
        </aside>
    </div>
    <footer>
        <!-- Footer -->
        <div>
            <section id="about">
                <header>
                    <h3>About</h3>
                </header>
                <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut la</p>
            </section>
            <section id="blogroll">
                <header>
                    <h3>Blogroll</h3>
                </header>
                <ul>
                    <li><a href="#">NETTUTS+</a></li>
                    <li><a href="#">FreelanceSwitch</a></li>
                </ul>
            </section>
            <section id="popular">
                <header>
                    <h3>Popular</h3>
                </header>
                <ul>
                    <li><a href="#">This is the title of a blog post</a></li>
                    <li><a href="#">Lorem ipsum dolor sit amet</a></li>
                    <li><a href="#">Consectetur adipisicing elit, sed do eiusmod</a></li>
                </ul>
            </section>
        </div>
    </footer>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/Scripts/shauli")
    @RenderSection("scripts", required: false)
    <script async defer
            src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCarSqkP2bpqHs05UwR8l47zOA2psWKkEQ &callback=initMap">
    </script>
    <script src="https://d3js.org/d3.v4.js"></script>
</body>
</html>